/* Generated by AN DISI Unibo */ 
package it.unibo.temperatureactor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Temperatureactor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
				val currentPlant = `it.greengers`.potserver.core.CurrentPlant.currentPlant
				var tempSensor : InputSensor<Double>
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("TemperatureActor: started")
					}
				}	 
			}
		}
}
