/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package it.greengers.potnetcore

import it.greengers.potnetcore.controller.PotNetCoreCoreCoreController
import kotlinx.coroutines.runBlocking

fun main() {
    PotNetCoreCoreCoreController.welcome()
    println("PotNetCoreAppl | Application started")
    runBlocking {
        PotNetCoreCoreCoreController.TERMINATE_CHANNEL.receive()
    }
    println("PotNetCoreAppl | Application shuwdowned")
}
